Update Readme.md
metakgp/kronos pull request #5
Opened 2024-06-14 19:09 UTC by Ananya-m0140

Should anything more be added like logo,etc?

2024-06-15 04:55 UTC, proffapt requested changes
Keep the same order as in readme
- contact
- maintainer
- creator
- then markdown links

Don't deviate at all from the structure of readme. Also add other stuff, present in `.github` folder of the repository except workflows folder. Update LICENSE and add the section `additional documentation`

2024-06-15 04:55 UTC, proffapt commented on README.md
> +# Credits
https://github.com/metakgp/README.md/blob/256ba6d22b41617eb1b4223d12815260b038903d/README.md?plain=1#L159

Change the section like this. Credit @spookbite.

2024-06-15 04:55 UTC, proffapt commented on README.md
> +# Maintainer(s)
https://github.com/metakgp/README.md/blob/256ba6d22b41617eb1b4223d12815260b038903d/README.md?plain=1#L154

Don't forget these one liner description for this and creator section as well.

2024-06-15 04:55 UTC, proffapt commented on README.md
> +[issues-shield]: https://img.shields.io/github/issues/metakgp/gyft.svg?style=for-the-badge
```suggestion
[issues-shield]: https://img.shields.io/github/issues/metakgp/kronos2.0.svg?style=for-the-badge
```

2024-06-15 04:55 UTC, proffapt commented on README.md
> +[stars-shield]: https://img.shields.io/github/stars/metakgp/gyft.svg?style=for-the-badge
```suggestion
[stars-shield]: https://img.shields.io/github/stars/metakgp/kronos2.0.svg?style=for-the-badge
```

2024-06-15 04:55 UTC, proffapt commented on README.md
> +[license-shield]: https://img.shields.io/github/license/metakgp/gyft.svg?style=for-the-badge
```suggestion
[license-shield]: https://img.shields.io/github/license/metakgp/kronos2.0.svg?style=for-the-badge
```

2024-06-15 06:55 UTC, Bikram-ghuku commented
The docker setup method doesn't work since the updated code is not pushed to the dockerhub....

2024-06-15 07:09 UTC, proffapt commented
> The docker setup method doesn't work since the updated code is not pushed to the dockerhub....

That will be done soon under #3

2024-06-16 12:23 UTC, proffapt requested changes
Files are in wrong folder. They should be in `.github` not in `.github/workflows`
Also, i don't think that you have added all the files. 
<img width="437" alt="image" src="https://github.com/metakgp/kronos/assets/86282911/d5365a54-b60d-4c1c-a74e-8812e5a5cd86">

- Add metaKGP logo as in that readme template
- rename it to kronos
- update all links from `kronos2.0` to `kronos`

2024-06-16 12:23 UTC, proffapt commented on README.md
> +
```suggestion

<p align="right">(<a href="#top">back to top</a>)</p>

```

2024-06-16 12:23 UTC, proffapt commented on README.md
> +# Getting started
```suggestion
## Getting started
```

2024-06-16 12:23 UTC, proffapt commented on README.md
> +### (Without Docker)
```suggestion
### Without docker
```

2024-06-16 12:23 UTC, proffapt commented on README.md
> +### Using Docker
```suggestion
### Using docker
```

2024-06-16 12:23 UTC, proffapt commented on README.md
>  You can go [here](https://kronos.streamlit.app/) for the live version of the project. Make your choices wisely :)
```suggestion
```

2024-06-16 12:23 UTC, proffapt commented on README.md
> +    <img width="90%" alt="image" src="https://github.com/Ananya-m0140/Git_KOSS/assets/153496011/f08c7a0a-1fd3-4c11-ab13-92bc120fea7f">
Update these `PROJECT_NAME` values

2024-06-16 16:52 UTC, proffapt approved these changes

2024-06-16 16:52 UTC, merged